[project]
name = "proyecto-redes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=38.2.0",
    "neo4j>=6.0.3",
    "pandas>=2.3.3",
    "polars>=1.36.0",
]
